//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperMSBuildRoslyn {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizableStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizableStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SuperMSBuildRoslyn.LocalizableStrings", typeof(LocalizableStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command to add package reference.
        /// </summary>
        internal static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a NuGet package reference to the project..
        /// </summary>
        internal static string AppFullName {
            get {
                return ResourceManager.GetString("AppFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create dependency graph file for project &apos;{0}&apos;. Cannot add package reference..
        /// </summary>
        internal static string CmdDGFileException {
            get {
                return ResourceManager.GetString("CmdDGFileException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to generate a temporary file for project &apos;{0}&apos;. Cannot add package reference. Clear the temp directory and try again..
        /// </summary>
        internal static string CmdDGFileIOException {
            get {
                return ResourceManager.GetString("CmdDGFileIOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FRAMEWORK.
        /// </summary>
        internal static string CmdFramework {
            get {
                return ResourceManager.GetString("CmdFramework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add the reference only when targeting a specific framework..
        /// </summary>
        internal static string CmdFrameworkDescription {
            get {
                return ResourceManager.GetString("CmdFrameworkDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add the reference without performing restore preview and compatibility check..
        /// </summary>
        internal static string CmdNoRestoreDescription {
            get {
                return ResourceManager.GetString("CmdNoRestoreDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command &apos;{0}&apos; only accepts a single argument but {1} were provided..
        /// </summary>
        internal static string CommandAcceptsOnlyOneArgument {
            get {
                return ResourceManager.GetString("CommandAcceptsOnlyOneArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not exist: {0}.
        /// </summary>
        internal static string FileDoesNotExist {
            get {
                return ResourceManager.GetString("FileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List all projects in a solution file..
        /// </summary>
        internal static string ListAppFullName {
            get {
                return ResourceManager.GetString("ListAppFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Add Command.
        /// </summary>
        internal static string NetAddCommand {
            get {
                return ResourceManager.GetString("NetAddCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option &apos;{0}&apos; only accepts a single argument but {1} were provided..
        /// </summary>
        internal static string OptionAcceptsOnlyOneArgument {
            get {
                return ResourceManager.GetString("OptionAcceptsOnlyOneArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove one or more projects from a solution file..
        /// </summary>
        internal static string RemoveAppFullName {
            get {
                return ResourceManager.GetString("RemoveAppFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The paths to the projects to remove from the solution..
        /// </summary>
        internal static string RemoveProjectPathArgumentDescription {
            get {
                return ResourceManager.GetString("RemoveProjectPathArgumentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROJECT_PATH.
        /// </summary>
        internal static string RemoveProjectPathArgumentName {
            get {
                return ResourceManager.GetString("RemoveProjectPathArgumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required argument missing for command: {0}.
        /// </summary>
        internal static string RequiredArgumentMissingForCommand {
            get {
                return ResourceManager.GetString("RequiredArgumentMissingForCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required argument missing for option: {0}.
        /// </summary>
        internal static string RequiredArgumentMissingForOption {
            get {
                return ResourceManager.GetString("RequiredArgumentMissingForOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required command was not provided..
        /// </summary>
        internal static string RequiredCommandWasNotProvided {
            get {
                return ResourceManager.GetString("RequiredCommandWasNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The solution file to operate on. If not specified, the command will search the current directory for one..
        /// </summary>
        internal static string SolutionArgumentDescription {
            get {
                return ResourceManager.GetString("SolutionArgumentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SLN_FILE.
        /// </summary>
        internal static string SolutionArgumentName {
            get {
                return ResourceManager.GetString("SolutionArgumentName", resourceCulture);
            }
        }
    }
}
